
name: MSBuild

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Build configuration'
        required: true
        default: 'Release'
        type: choice
        options:
          - Debug-x64
          - Profile-x64
          - Release-x64

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Clone and bootstrap vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git vcpkg
        ./vcpkg/bootstrap-vcpkg.bat

    - name: Setup CMake
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: cmake --preset=${{ github.event.inputs.configuration || 'Release-x64' }} -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: cmake --build --preset=${{ github.event.inputs.configuration || 'Release-x64' }} -j
